### ISSUE TITLE
documentation creation

### ISSUE THREAD

**Issue by lpatiny** [mljs/arrayxy-uniquex#1]
I successfully created the project with cheminfo-tools. Really great !

Just have one small problem. The documentation on github is not linked correctly. I try the `cheminfo doc` but seems not enough.

I also tried `cheminfo doc -p` but still the gh-pages branch is not created and I guess it should be.

I also wonder if each time we do

`cheminfo publish` if the doc should not be automatically updated. Not sure this is the case currently.

**Comment by stropitek** [comment]
The doc is no longer generated on the gh-pages
Activate the the option in the repo's preferences that make master/docs the documentation page
